const products = [
  {
    _id: '1',
    name: 'Full Sleeves Meow Hoodie for Men & Women',
    image: './images/image1.jpg',
    price: 950,
    availableSizes: ['X', 'L', 'XL', 'XXL'],
    rating: 4.5,
  },
  {
    _id: '2',
    name: 'Full Sleeves MFS Hoodie for Men & Women',
    image: './images/image2.jpg',
    price: 850,
    availableSizes: ['X', 'L', 'XL'],
    rating: 4.5,
  },
  {
    _id: '3',
    name: 'Full Sleeves BUCH Hoodie for Men & Women',
    image: './images/image3.jpg',
    price: 750,
    availableSizes: ['XL', 'XXL'],
    rating: 4.5,
  },
  {
    _id: '4',
    name: 'Full Sleeves Black Panther Hoodie for Men & Women',
    image: './images/image4.jpg',
    price: 950,
    availableSizes: ['L', 'XL'],
    rating: 4.5,
  },
  {
    _id: '5',
    name: 'Full Sleeves Stylist Hoodie for Men & Women',
    image: './images/image5.jpg',
    price: 1050,
    availableSizes: ['X', 'L', 'XXL'],
    rating: 4.5,
  },
  {
    _id: '6',
    name: 'Trendy Hoodie for Men & Women',
    image: './images/image6.jpg',
    price: 550,
    availableSizes: ['L', 'XXL'],
    rating: 4.5,
  },
  {
    _id: '7',
    name: 'Marijuana Hoodie for Men & Women',
    image: './images/image7.jpg',
    price: 750,
    availableSizes: ['X', 'L', 'XL', 'XXL'],
    rating: 4.5,
  },
  {
    _id: '8',
    name: 'Full Sleeves Blue Hoodie for Men ',
    image: './images/image8.jpg',
    price: 1250,
    availableSizes: ['XL', 'XXL'],
    rating: 4.5,
  },
];

export default products;
